### ISSUE TITLE
sorry but i really don't understand how to deploy my element to this site?

### ISSUE THREAD

**Issue by markhuang1212** [marcus7777/open-elements.org#25]

**Comment by tonyedwardspz** [comment]
You need to make a pull request against one of the following repos. Your element will be pulled in during the next build of the site.

 - https://github.com/marcus7777/iron-elements#master
 - https://github.com/marcus7777/paper-elements-1#master
 - https://github.com/marcus7777/molecules#master
 - https://github.com/marcus7777/utilities#master
 - https://github.com/marcus7777/development#master

I think this is something @marcus7777 is working on streamlining in the near future?

**Comment by markhuang1212** [comment]
Include my element inside that bower.json? That's all I need to do, right?

**Comment by tonyedwardspz** [comment]
Yeah.

**Comment by markhuang1212** [comment]
@tonyedwardspz thanks a lot

**Comment by tonyedwardspz** [comment]
No problem. Welcome to open-elements!
