### ISSUE TITLE
Remove Polymer logo to avoid confusion?

### ISSUE THREAD

**Issue by tjsavage** [marcus7777/open-elements.org#8]
Love the re-use of the Polymer elements catalog code - could you remove the Polymer logo and lockup to avoid any confusion though?

![image](https://cloud.githubusercontent.com/assets/348551/9472566/08e4f094-4b0b-11e5-9e91-2dcdc8e88dee.png)

**Comment by marcus7777** [comment]
@tjsavage lockup?

**Comment by marcus7777** [comment]
swich to Inconsolata, monospace as main font, update logo
